Add_user_name
YevgenPy/a pull request #4
Opened 2022-03-29 19:01 UTC by YevgenPy

Dobavil Username

2022-03-29 19:11 UTC, denikus requested changes

2022-03-29 19:11 UTC, denikus commented on app/models/user.rb
> +  validate :validate_username
та для уникальности полей есть стандартные валидации, ненужно свою писать

2022-03-29 19:12 UTC, YevgenPy commented on app/models/user.rb
> +  validate :validate_username
такую нашел просто

2022-03-29 19:17 UTC, denikus commented on app/models/user.rb
> +  validate :validate_username
перечитай про валидации и примеры посмотри https://guides.rubyonrails.org/active_record_validations.html

2022-03-30 17:45 UTC, denikus approved these changes

2022-03-30 17:50 UTC, merged