Elasticsearch
YevgenPy/a pull request #6
Opened 2022-04-13 09:58 UTC by YevgenPy

2022-04-18 16:56 UTC, denikus requested changes

2022-04-18 16:56 UTC, denikus commented on Gemfile
> +gem "elasticsearch-model"
а эти все джемы точно нужны? одного searchkick не хватило?

2022-04-18 17:46 UTC, YevgenPy commented on Gemfile
> +gem "elasticsearch-model"
Можливо я не точно зрозумів з документації гема,  але мені здалося, що там ще 1 потрібен. Інші зайві, видалив.

2022-04-19 16:46 UTC, denikus approved these changes

2022-04-20 08:55 UTC, merged